# Generated by Django 2.2.1 on 2019-11-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_prod_arrival',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prodd_img', models.ImageField(upload_to='pics')),
                ('prod_category', models.CharField(max_length=40)),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_price', models.IntegerField()),
                ('offer', models.BooleanField()),
            ],
        ),
    ]
