# Generated by Django 3.0.2 on 2020-01-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_accesories_clothing_men_collection_other_women_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesories',
            name='desc',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='desc',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='men_collection',
            name='desc',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='other',
            name='desc',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='women_collection',
            name='desc',
            field=models.TextField(max_length=500),
        ),
    ]
