# Generated by Django 3.0.2 on 2020-01-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_auto_20200123_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
                ('offer', models.BooleanField()),
            ],
        ),
    ]
