# Generated by Django 3.0.2 on 2020-01-26 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_shop_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accesories',
        ),
        migrations.DeleteModel(
            name='Clothing',
        ),
        migrations.DeleteModel(
            name='Men_Collection',
        ),
        migrations.DeleteModel(
            name='Other',
        ),
        migrations.DeleteModel(
            name='Women_Collection',
        ),
    ]
