# Generated by Django 2.0.2 on 2020-02-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New_prod_arrival',
        ),
    ]
